#!/usr/bin/env python3
"""Reproducible frontend build — bundle src/engram.jsx, inline into a self-contained index.html.

No node/npm at runtime. Uses the esbuild standalone binary + pinned npm deps
(react / react-dom / scheduler / lucide-react) vendored into ``frontend/.build/`` (gitignored).
Deps are reused if cached, else copied from a surviving build env, else downloaded from
registry.npmjs.org. Output (``app.bundle.js`` + ``index.html``) is committed; this script is the
reproducibility aid (the v0.9 "rebuild then re-inline" step was previously manual/undocumented).

    python frontend/build.py

Pipeline: locate esbuild -> ensure deps -> esbuild --bundle --jsx=automatic --minify ->
inline vendor/tailwind.js (head) + app.bundle.js (body) into index.html.
"""
from __future__ import annotations

import glob
import io
import os
import shutil
import subprocess
import tarfile
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "src", "engram.jsx")
VENDOR_TW = os.path.join(HERE, "vendor", "tailwind.js")
BUILD = os.path.join(HERE, ".build")            # gitignored cache (node_modules + work copy)
NODE_MODULES = os.path.join(BUILD, "node_modules")
OUT_BUNDLE = os.path.join(HERE, "app.bundle.js")
OUT_INDEX = os.path.join(HERE, "index.html")

# Exact versions the committed bundle was built with (keep in sync if upgrading).
PINS = {"react": "18.3.1", "react-dom": "18.3.1", "scheduler": "0.23.2", "lucide-react": "1.21.0"}
ESBUILD_VER = "0.21.5"
REGISTRY = "https://registry.npmjs.org"
ESBUILD_CANDIDATES = ["/tmp/package/bin/esbuild", os.path.join(BUILD, "esbuild", "bin", "esbuild")]


def _download_tar(url: str, dest: str) -> None:
    """Download an npm .tgz and extract its ``package/`` root into ``dest``."""
    os.makedirs(dest, exist_ok=True)
    with urllib.request.urlopen(url, timeout=90) as r:
        data = r.read()
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tf:
        for m in tf.getmembers():
            if m.name.startswith("package/"):
                m.name = m.name[len("package/"):]
                if m.name:
                    tf.extract(m, dest)


def find_esbuild() -> str:
    for c in [*ESBUILD_CANDIDATES, shutil.which("esbuild") or ""]:
        if c and os.path.exists(c):
            return c
    dest = os.path.join(BUILD, "esbuild")
    _download_tar(f"{REGISTRY}/@esbuild/linux-x64/-/linux-x64-{ESBUILD_VER}.tgz", dest)
    binp = os.path.join(dest, "bin", "esbuild")
    os.chmod(binp, 0o755)
    return binp


def ensure_dep(name: str, ver: str) -> None:
    target = os.path.join(NODE_MODULES, name)
    if os.path.exists(os.path.join(target, "package.json")):
        return
    # fast path: copy from a surviving build env (another session's scratchpad), if any.
    for cand in glob.glob(f"/tmp/claude-*/**/fe-build/node_modules/{name}", recursive=True):
        if os.path.exists(os.path.join(cand, "package.json")):
            shutil.copytree(cand, target)
            return
    base = name.split("/")[-1]
    _download_tar(f"{REGISTRY}/{name}/-/{base}-{ver}.tgz", target)


def build_bundle(esbuild: str) -> None:
    os.makedirs(BUILD, exist_ok=True)
    for n, v in PINS.items():
        ensure_dep(n, v)
    # Copy the source next to node_modules so esbuild resolves bare specifiers from the cache.
    work_src = os.path.join(BUILD, "engram.jsx")
    shutil.copyfile(SRC, work_src)
    subprocess.run(
        [esbuild, work_src, "--bundle", "--jsx=automatic", "--format=iife", "--minify",
         '--define:process.env.NODE_ENV="production"', "--outfile=" + OUT_BUNDLE],
        check=True, cwd=BUILD,
    )


def inline_index() -> None:
    """Emit a self-contained index.html: inlined Tailwind (head) + inlined app bundle (body)."""
    with open(VENDOR_TW, encoding="utf-8") as f:
        tw = f.read()
    with open(OUT_BUNDLE, encoding="utf-8") as f:
        app = f.read()
    html = (
        "<!doctype html>\n"
        "<!-- Engram — self-contained single file: Tailwind + React + icons + app ALL inlined.\n"
        "     GENERATED by frontend/build.py from src/engram.jsx — do not hand-edit; rebuild instead. -->\n"
        '<html lang="zh">\n'
        "  <head>\n"
        '    <meta charset="utf-8" />\n'
        '    <meta name="viewport" content="width=device-width, initial-scale=1" />\n'
        "    <title>Engram — continual-learning personal agent</title>\n"
        "    <style>html,body{margin:0;background:#EFEDE8}#root{min-height:100vh}</style>\n"
        "    <script>\n" + tw + "\n</script>\n"
        "  </head>\n"
        "  <body>\n"
        '    <div id="root"></div>\n'
        "    <noscript>本原型需要启用 JavaScript。</noscript>\n"
        "    <script>\n" + app + "\n</script>\n"
        "  </body>\n"
        "</html>\n"
    )
    with open(OUT_INDEX, "w", encoding="utf-8") as f:
        f.write(html)


def main() -> None:
    esbuild = find_esbuild()
    build_bundle(esbuild)
    inline_index()
    print(f"esbuild: {esbuild}")
    print(f"built  : {OUT_BUNDLE} ({os.path.getsize(OUT_BUNDLE)} bytes)")
    print(f"inlined: {OUT_INDEX} ({os.path.getsize(OUT_INDEX)} bytes)")


if __name__ == "__main__":
    main()
